# Generated by Django 4.0.6 on 2022-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programmingQ',
            fields=[
                ('qno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=500)),
                ('optiona', models.CharField(max_length=300)),
                ('optionb', models.CharField(max_length=300)),
                ('optionc', models.CharField(max_length=300)),
                ('optiond', models.CharField(max_length=300)),
                ('ans', models.CharField(max_length=1)),
            ],
        ),
    ]
