# Generated by Django 4.1.5 on 2023-02-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Test', '0004_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='main_test_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Of_Sub_Catagory', models.CharField(max_length=100)),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Test.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Test.main_test_categories'),
        ),
    ]
