# Generated by Django 4.1.5 on 2023-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Test', '0005_category_main_test_categories_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_test_categories',
            name='img',
            field=models.ImageField(default='', upload_to='test_images/'),
        ),
    ]
